#ifndef HINAPE_CUBBYFLOW_HOW_TO_USE_GENERATOR_H
#define HINAPE_CUBBYFLOW_HOW_TO_USE_GENERATOR_H

#include "CubbyHDKClassGenerator.h"

// CLASS name: GAS_CF_NEW_SOLVER
NEW_CUBBY_MICRPSOLVER_CLASS(
		NEW_SOLVER,
		NEW_GETSET_PARAMETER(MyInt, GETSET_DATA_FUNCS_I) \
        NEW_GETSET_PARAMETER(MyFloat, GETSET_DATA_FUNCS_F) \
        NEW_GETSET_PARAMETER(MyString, GETSET_DATA_FUNCS_S) \
        NEW_GETSET_PARAMETER(MyBool, GETSET_DATA_FUNCS_B) \
        NEW_GETSET_PARAMETER(MyVector3F, GETSET_DATA_FUNCS_V3) \
        NEW_GETSET_PARAMETER(MyVector3I, GETSET_DATA_FUNCS_V3) \

				int local_int = 0;
				std::string local_string;

				void _test_function();
)

// CLASS name: SIM_CF_NEW_DATA
NEW_CUBBY_DATA_CLASS(
		NEW_DATA,
		NEW_GETSET_PARAMETER(MyInt, GETSET_DATA_FUNCS_I) \
        NEW_GETSET_PARAMETER(MyFloat, GETSET_DATA_FUNCS_F) \
        NEW_GETSET_PARAMETER(MyString, GETSET_DATA_FUNCS_S) \
        NEW_GETSET_PARAMETER(MyBool, GETSET_DATA_FUNCS_B) \
        NEW_GETSET_PARAMETER(MyVector3F, GETSET_DATA_FUNCS_V3) \
        NEW_GETSET_PARAMETER(MyVector3I, GETSET_DATA_FUNCS_V3) \

				int local_int = 0;
				std::string local_string;

				void _test_function();
)

#endif //HINAPE_CUBBYFLOW_HOW_TO_USE_GENERATOR_H
