#ifndef HINAPE_GAS_HINA_UPDATENEIGHBOR_H
#define HINAPE_GAS_HINA_UPDATENEIGHBOR_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		UpdateNeighbor,
		NEW_GETSET_PARAMETER(Gravity, GETSET_DATA_FUNCS_V3)
)

#endif //HINAPE_GAS_HINA_UPDATENEIGHBOR_H
