#ifndef HINAPE_GAS_HINA_GRAVITYFORCE_H
#define HINAPE_GAS_HINA_GRAVITYFORCE_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		GravityForce,
		NEW_GETSET_PARAMETER(Gravity, GETSET_DATA_FUNCS_V3)
)

#endif //HINAPE_GAS_HINA_GRAVITYFORCE_H
