#ifndef HINAPE_CUBBYFLOW_GAS_HINA_SEMIIMPLICITEULER_H
#define HINAPE_CUBBYFLOW_GAS_HINA_SEMIIMPLICITEULER_H

class GAS_Hina_SemiImplicitEuler
{

};

#endif //HINAPE_CUBBYFLOW_GAS_HINA_SEMIIMPLICITEULER_H
