#ifndef HINAPE_CUBBYFLOW_GAS_HINA_COMPUTESUBSTEPS_H
#define HINAPE_CUBBYFLOW_GAS_HINA_COMPUTESUBSTEPS_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		ComputeSubsteps,
)

#endif //HINAPE_CUBBYFLOW_GAS_HINA_COMPUTESUBSTEPS_H
