#ifndef HINAPE_GAS_HINA_CUBICSEMILAGRANGIAN_H
#define HINAPE_GAS_HINA_CUBICSEMILAGRANGIAN_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		CubicSemiLagrangian,
)

#endif //HINAPE_GAS_HINA_CUBICSEMILAGRANGIAN_H
