#ifndef HINAPE_GAS_HINA_PSEUDOVISCOSITY_H
#define HINAPE_GAS_HINA_PSEUDOVISCOSITY_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		PseudoViscosity,
)

#endif //HINAPE_GAS_HINA_PSEUDOVISCOSITY_H
