#ifndef HINAPE_GAS_HINA_COLLISIONSOLVE_H
#define HINAPE_GAS_HINA_COLLISIONSOLVE_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		CollisionSolve,
)

#endif //HINAPE_GAS_HINA_COLLISIONSOLVE_H
