#ifndef HINAPE_CUBBYFLOW_GAS_HINA_PCISPHPRESSURE_H
#define HINAPE_CUBBYFLOW_GAS_HINA_PCISPHPRESSURE_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		PCISPHPressure,
)

#endif //HINAPE_CUBBYFLOW_GAS_HINA_PCISPHPRESSURE_H
