#ifndef HINAPE_GAS_HINA_UPDATENEIGHBOR_H
#define HINAPE_GAS_HINA_UPDATENEIGHBOR_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		UpdateNeighbor,
)

#endif //HINAPE_GAS_HINA_UPDATENEIGHBOR_H
