#ifndef HINAPE_CUBBYFLOW_GAS_HINA_READNEIGHBOR_H
#define HINAPE_CUBBYFLOW_GAS_HINA_READNEIGHBOR_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		ReadNeighbor,
)

#endif //HINAPE_CUBBYFLOW_GAS_HINA_READNEIGHBOR_H
