#ifndef HINAPE_SIM_HINA_PLANE_H
#define HINAPE_SIM_HINA_PLANE_H

#include "HinaHDKClassGenerator.h"
#include "Core/Geometry/Plane.hpp"

NEW_HINA_GEOMETRY_CLASS(
		Plane,
		CubbyFlow::Plane3Ptr,
		NEW_GETSET_PARAMETER(Center, GETSET_DATA_FUNCS_V3)
		NEW_GETSET_PARAMETER(Normal, GETSET_DATA_FUNCS_V3)
		NEW_GETSET_PARAMETER(IsNormalFlipped, GETSET_DATA_FUNCS_B)
)

#endif //HINAPE_SIM_HINA_PLANE_H
