#ifndef HINAPE_SIM_HINA_BOX_H
#define HINAPE_SIM_HINA_BOX_H

#include "HinaHDKClassGenerator.h"
#include "Core/Geometry/Box.hpp"

NEW_HINA_GEOMETRY_CLASS(
		Box,
		CubbyFlow::Box3Ptr,
		NEW_GETSET_PARAMETER(Center, GETSET_DATA_FUNCS_V3)
		NEW_GETSET_PARAMETER(Extent, GETSET_DATA_FUNCS_V3)
		NEW_GETSET_PARAMETER(IsNormalFlipped, GETSET_DATA_FUNCS_B)
)

#endif //HINAPE_SIM_HINA_BOX_H
