#ifndef HINAPE_GAS_HINA_SEMIIMPLICITEULER_H
#define HINAPE_GAS_HINA_SEMIIMPLICITEULER_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		SemiImplicitEuler,
)

#endif //HINAPE_GAS_HINA_SEMIIMPLICITEULER_H
