#ifndef HINAPE_GAS_HINA_UPDATEDENSITY_H
#define HINAPE_GAS_HINA_UPDATEDENSITY_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		UpdateDensity,
)

#endif //HINAPE_GAS_HINA_UPDATEDENSITY_H
