#ifndef HINAPE_CUBBYFLOW_GAS_HINA_SEMILAGRANGIAN_H
#define HINAPE_CUBBYFLOW_GAS_HINA_SEMILAGRANGIAN_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		SemiLagrangian,
)

#endif //HINAPE_CUBBYFLOW_GAS_HINA_SEMILAGRANGIAN_H
