#ifndef HINAPE_CUBBYFLOW_GAS_HINA_SPHPRESSURE_H
#define HINAPE_CUBBYFLOW_GAS_HINA_SPHPRESSURE_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		SPHPressure,
)

#endif //HINAPE_CUBBYFLOW_GAS_HINA_SPHPRESSURE_H
