#ifndef HINAPE_GAS_HINA_COMMITALLCACHES_H
#define HINAPE_GAS_HINA_COMMITALLCACHES_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		CommitAllCaches,
)

#endif //HINAPE_GAS_HINA_COMMITALLCACHES_H
