#ifndef HINAPE_GAS_HINA_CONFIGUREFORSPH_H
#define HINAPE_GAS_HINA_CONFIGUREFORSPH_H

#include "HinaHDKClassGenerator.h"

NEW_HINA_MICRPSOLVER_CLASS(
		ConfigureForSPH,
)

#endif //HINAPE_GAS_HINA_CONFIGUREFORSPH_H
